logging:
  file:
    name: pbems.log
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pbems?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

login:
  ignoreUrls: /api/login, /api/ads